# Generated by Django 5.2.9 on 2026-01-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PandharRaste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taluka", models.CharField(max_length=100, verbose_name="तालुका")),
                (
                    "geo_tag_roads",
                    models.IntegerField(default=0, verbose_name="Geo-tag केलेले रस्ते"),
                ),
                (
                    "cleared_roads",
                    models.IntegerField(
                        default=0, verbose_name="अतिक्रमण काढलेले रस्ते"
                    ),
                ),
                (
                    "cleared_length_km",
                    models.FloatField(
                        default=0.0, verbose_name="अतिक्रमण काढलेली लांबी (कि.मी.)"
                    ),
                ),
                (
                    "farmers_benefited",
                    models.IntegerField(default=0, verbose_name="लाभार्थी शेतकरी"),
                ),
            ],
            options={
                "verbose_name": "पांढर रस्ते",
                "verbose_name_plural": "पांढर रस्ते",
                "ordering": ["taluka"],
            },
        ),
    ]
