# Generated by Django 5.2.9 on 2026-01-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pandharraste",
            name="geo_tag_length_km",
            field=models.FloatField(
                default=0.0,
                verbose_name="अतिक्रमित व Geo-tag रस्त्यांची लांबी (कि.मी.)",
            ),
        ),
    ]
