# Generated by Django 5.2.9 on 2026-01-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0002_pandharraste_geo_tag_length_km"),
    ]

    operations = [
        migrations.CreateModel(
            name="EHaqq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "taluka",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="तालुका"
                    ),
                ),
                (
                    "total_applications",
                    models.IntegerField(default=0, verbose_name="एकूण अर्ज"),
                ),
                (
                    "approved_applications",
                    models.IntegerField(default=0, verbose_name="स्वीकारित अर्ज"),
                ),
                (
                    "rejected_applications",
                    models.IntegerField(default=0, verbose_name="अस्वीकारित अर्ज"),
                ),
                (
                    "pending_applications",
                    models.IntegerField(default=0, verbose_name="प्रलंबित अर्ज"),
                ),
                (
                    "approved_percentage",
                    models.FloatField(default=0.0, verbose_name="स्वीकारित अर्ज (%)"),
                ),
                (
                    "rejected_percentage",
                    models.FloatField(default=0.0, verbose_name="अस्वीकारित अर्ज (%)"),
                ),
                (
                    "pending_percentage",
                    models.FloatField(default=0.0, verbose_name="प्रलंबित अर्ज (%)"),
                ),
                (
                    "period_work_count",
                    models.IntegerField(default=0, verbose_name="कालावधीतील कामकाज"),
                ),
            ],
            options={
                "verbose_name": "ई-हक्क",
                "verbose_name_plural": "ई-हक्क",
                "ordering": ["taluka"],
            },
        ),
    ]
