# Generated by Django 5.2.9 on 2026-01-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0003_ehaqq"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgriStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "taluka",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="तालुका"
                    ),
                ),
                (
                    "total_villages",
                    models.IntegerField(default=0, verbose_name="एकूण गावे"),
                ),
                (
                    "total_farmers",
                    models.IntegerField(default=0, verbose_name="एकूण शेतकरी"),
                ),
                (
                    "farmers_with_id_created",
                    models.IntegerField(
                        default=0, verbose_name="फार्मर आयडी तयार केलेले शेतकरी"
                    ),
                ),
                (
                    "farmers_pending_id",
                    models.IntegerField(
                        default=0,
                        verbose_name="फार्मर आयडी तयार करण्यावर शिल्लक शेतकरी",
                    ),
                ),
                (
                    "completion_percentage",
                    models.FloatField(default=0.0, verbose_name="टक्केवारी"),
                ),
            ],
            options={
                "verbose_name": "ॲग्रीस्टॅक",
                "verbose_name_plural": "ॲग्रीस्टॅक",
                "ordering": ["taluka"],
            },
        ),
    ]
